### ISSUE TITLE
Match editor markup to wp-admin editor where possible

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS-Editor#103]
We should try to match up the HTML output that the wp-admin editor generates vs. what the editor library generates. A few things I noticed:

 * Library adds `<br>` tags, where wp-admin just inserts line breaks
 * Library seems to use outdated tag names, like `<b>` instead of `<strong>`
 * Library seems to add a ton of `<div>` tags as well.

**Comment by bummytime** [comment]
@meremagee can we move all shortcode-related stuff from this issue to #85?

**Comment by meremagee** [comment]
@bummytime if there's nothing we can do to make it _work_ upon publish as it's supposed to, then I suppose we need to punt. The diff between this and #85 is that 85 includes crafting a nice ui/ux for adding embeds into the app whereas this has to do with rending shortcodes and embeds improperly (differently than wp-admin)

**Comment by bummytime** [comment]
@meremagee Gotcha. I am just trying to make more issues more bite-size. :-)

**Comment by meremagee** [comment]
created separate issues for each with a master issue for tracking here: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/501

closing this now-massive post in favor of the cleaned up versions
