### ISSUE TITLE
Images don't show up when the device is offline.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS-Editor#147]
Images don't show up at all when the device is offline (ie: it has no network connection).  A placeholder would be a nice way to show an image is supposed to be displayed.

**Comment by bummytime** [comment]
Because of the new retry feature (https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/348), the user will see the image with a failed overlay. Closing this for now.
