### ISSUE TITLE
Crasher changing post status

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS-Editor#255]
### Stacktrace ###

<pre>BasePost;setStatusTitle:;BasePost.m;86
PostSettingsViewController;showPostStatusSelector;PostSettingsViewController.m;757
PostSettingsSelectionViewController;tableView:didSelectRowAtIndexPath:;PostSettingsSelectionViewController.m;110</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0xd00000000444000c <x-coredata://DB37D133-7A7F-498E-A824-77D271BCC883/Post/p273>''

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/34115/app_versions/101/crash_reasons/20033224](https://rink.hockeyapp.net/manage/apps/34115/app_versions/101/crash_reasons/20033224)

**Comment by meremagee** [comment]
Haven't been able to repro in recent builds.
