### ISSUE TITLE
Can't scroll after adding media

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#301]
- add an image (either after text or as first thing)
- try to scroll to bottom of post
- add cursor after image
- type words
- try to scroll to caret position to see what you're typing
- can't :(

video: https://lookback.io/watch/mkkWbc7MPeX8LwQcu

**Comment by meremagee** [comment]
still get this in latest 4.7 beta build, ios7

**Comment by meremagee** [comment]
repro'ed on ios8/ipad mini

**Comment by diegoreymendez** [comment]
We should get this little guy a suit.
![bug-vs-feature jpg](https://cloud.githubusercontent.com/assets/1836005/5741019/40512d78-9be7-11e4-9644-2ff1e63889d0.gif)

Jokes aside... I'm on it.

**Comment by diegoreymendez** [comment]
@meremagee - I'm leaving this ticket for you to close, since it's proving to be a very recurrent issue, and I'm not entirely sure the case I fixed is the same you're seeing.

This is not included in v4.7 due to timing, but it should be testable in the next internal release.

**Comment by meremagee** [comment]
added "resolved > test" label to help me sort instead of keeping this open.

**Comment by meremagee** [comment]
still happens - iphone 5s & ipad 2, ios7

**Comment by diegoreymendez** [comment]
Fixed.

**Comment by bummytime** [comment]
@diegoreymendez 

> Fixed.

Famous last words.... :grinning:  (kidding)

**Comment by meremagee** [comment]
ios7 works because it dismisses keyboard upon img insertion. good enough work-around for now. :+1:

**Comment by diegoreymendez** [comment]
@meremagee - Actually it should work anyway.  The keyboard remaining hidden was introduced by another PR recently but is coincidential - it's a separate bug we should be able to resolve regardless.

**Comment by diegoreymendez** [comment]
@meremagee - This is the issue for the [keyboard problem](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/535).
