### ISSUE TITLE
Animation jank when switching from Title to Post (back and forth)

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-iOS-Editor#324]
Post body jumps up then back down when switching back from Title

**Comment by thianhlu** [comment]
Also happens when switching from html mode to visual mode if the cursor is on first line

**Comment by diegoreymendez** [comment]
Fixed again, after a regression caused by fixing [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/396).

**Comment by diegoreymendez** [comment]
PS: not included in v4.7 due to timing
