### ISSUE TITLE
Placeholder img when media fails

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#361]
Right now, if on a poor connection (in my case, 2-3 bars on mobile lte... not the worst), uploading media on visual editor:
- adds local placeholder image
- shows "uploading media" spinner in nav bar
- [upload fails](https://cloudup.com/imRkarDOyZ8) (every time)
- placeholder image [remains in post](https://cloudup.com/iLTr8c2QA3u) even though remote upload has failed
- previewing or publishing post [shows square](https://cloudup.com/i-HT3Rr2C2z) instead of placeholder img
- local source [still embedded](https://cloudup.com/ibLxmeeKg4Q) in post

while adding media on prod editor
- works extremely quickly - within 1-2 seconds - embedding [url to img](https://cloudup.com/i4f8j0bEJda) wp media library link

We should handle failed uploads/placeholder images more gracefully. Some ideas:
- figure out why media uploads take longer on visual editor & fix problem entirely (https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/344#issuecomment-62081915) 
- show "upload has failed alert" and just remove the corresponding local img placeholder
- show that has failed in UI on placeholder; then don't publish in post (as square)
- show that has failed in UI on placeholder and tap to retry

**Comment by SergioEstevao** [comment]
This should be solved on build 4.7
