### ISSUE TITLE
Tapping list format bar button does not start a new list on new/empty posts

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS-Editor#367]
This issue affects both ordered and unordered lists when the post body is empty. When you type some text before pressing the button, it works as expected

From a user:

> Can’t make the first piece of content in new post a list (bulleted or numbered).
>
1. Start new post.
2. Enter title.
3. Tap in content area.
4. Tap list button.
>
I saw: nothing happen.
>
I expected: a bullet or number to appear, ready to become a list. :(

Here is a video of the issue:

https://cloudup.com/cyBGGrXFqNF

**Comment by meremagee** [comment]
related: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/360
