### ISSUE TITLE
Format bar disabled if post drafted/published on web

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#372]
repro:
- create post on wp-admin
- save or publish post
- open post in mobile app
- hit "edit"
- keyboard slides up but format bar is missing
- fixed by dismissing keyboard then hitting edit again
- then, if you do edit, "update"/"post" button is disabled

no format bar
![](https://cloudup.com/iYxJDm2uHgg+)

update/post button seems confused and disabled after edited
![](https://cloudup.com/iHeqUn7wQaH+)

**Comment by bummytime** [comment]
Being realistic and taking my name off this for now.

**Comment by meremagee** [comment]
appears to be fixed (tested ios7 and ios8)
