### ISSUE TITLE
Add/edit image meta data

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#427]
Consolidates https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/194, https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/104, https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/46, https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/23, and https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/336

We don't have prior experience/data with image meta data on iOS, so implementation would be done from scratch. Wanted to log here so that we could start shaping design for the implementation that @aerych is working on.

Image meta options in wp-admin: https://cloudup.com/im9Af0GJVhw
- image alignment: left, center, right, none
- image size: https://cloudup.com/iiZv-FliyQs
- title (text)
- caption (text)
- alt (text)
- description (textarea)
- link to: https://cloudup.com/iiO-icBrF2W
- displayed (non-editable): date uploaded, img direct url

UX needs to be compatible with any actions performed for media uploading, i.e. pause, cancel, retry. WIP thoughts:
- tap on media during upload: pause > option to cancel
- tap on failed media: retry
- tap on fully uploaded media: edit meta data

**Comment by thianhlu** [comment]
@aerych I will update with pencil icon as well as putting thumbnail in the options screen.

**Comment by thianhlu** [comment]
@aerych you wanted something like this?

![](https://cloudup.com/cQaQh9G05Kw+)

**Comment by aerych** [comment]
@thianhlu That'll work :)  I'd envisioned a large thumb and centered but maybe that approach would take up too much space. Its probably best to show as many of the options as possible.  

Maybe we can move the thumb cell above the Details header since its not editable where as all the other options are?

**Comment by bummytime** [comment]
> Would it be okay to move the thumb cell above the Details header since its not editable where as all the other options are?

@thianhlu did you give @aerych an answer for this?

**Comment by aerych** [comment]
> I will update with pencil icon 

@thianhlu Is the plan to still go with this icon? Not clear if the intention was to just use the icon or still show text as well.

**Comment by thianhlu** [comment]
Yup sorry haven't done either yet. I will provide an updated version today.

**Comment by thianhlu** [comment]
@aerych @bummytime 

With image at top. 
![](https://cloudup.com/cDZy91gNDVp+)

Perhaps we display both text and icon on large images and just the icon on smaller images. I needed to add the circle cause the pencil by itself felt out of place and odd. lmk
![](https://cloudup.com/carmmoWr6PJ+)

**Comment by aerych** [comment]
@thianhlu Works for me!  

One last question. I think we probably don't need the Description field until we're hooked up to the user's media library since there is nothing in the image / caption markup to handle the description. Does this sound reasonable?

**Comment by meremagee** [comment]
makes sense to me to remove description given all inputs in the edit modal serve to update the image _locally_ and don't get fed back into the media library. Since description doesn't affect the markup in any way, won't be saved in the media library w/ the image object, and doesn't appear in the "edit" modal in wp-admin, it should be removed.

**Comment by thianhlu** [comment]
Sounds good @aerych. Also @bummytime mentioned we should keep this design similar to Image upload retry if we plan to keep the circle with icon.

**Comment by thianhlu** [comment]
@aerych here is svg https://cloudup.com/cmd2cAga83A

check out #474

**Comment by aerych** [comment]
Thanks for all the help @thianhlu @meremagee and @bummytime.  Closed this now that its PR is merged.
