### ISSUE TITLE
Post status change disabled for HTML

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#437]
On posts and pages. The HTML editor does not appear to trigger "updates" at all. There are 2 ways to see this:

Symptom 1:
- go to posts or pages
- create new or edit existing (tap edit)
- start editing/writing on visual editor
- switch to html editor
- add more content
- tap update/post from html
- notice that **no changes were stored from the html editor**- the only contents displayed will be those from the visual editor
- https://cloudup.com/ieUmhjEbEH8

Symptom 2:
- go to posts or pages
- create new or edit existing (tap edit)
- tap HTML first thing, before entering any
- start typing in HTML editor
- **notice that "post/update" continues to stay disabled** (does not appear to be triggering edit events)
- https://cloudup.com/caK3NTioJQl
- finish typing and nav back to visual mode by hitting html button
- notice post/update is now enabled
- post/update from visual
- post is updated with new content (since ultimately published from visual)

**Comment by diegoreymendez** [comment]
Fixed.

**Comment by diegoreymendez** [comment]
Not working properly, yet.  Need to apply some extra fixes.

**Comment by diegoreymendez** [comment]
Fixed.
