### ISSUE TITLE
Empty post publication

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#441]
Publishing empty posts fails on visual editor and crashes on legacy. Because I can't think of any reasons to allow publishing an empty post, let's disable post/publish until at least 1 character has been added to title or body.

Repro:
- Create a new post
- Tap options
- Tap tags or categories and add either a tag or category
- Go back to post and tap Post to publish
- Post "fails" on visual editor; **crashes** if legacy editor

Note from @koke - It will crash when generating the REST request because title is nil (if there's some content, title is an empty string instead).

**Comment by diegoreymendez** [comment]
Fixed.
