### ISSUE TITLE
Switch to HTML view when media fails

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#452]
Currently, we would display the code for img retry, which would be confusing for users.

@thianhlu shall we:
- just remove the images and retry code if a user navigates to HTML view after images have failed? (better rep of what would be published)
- throw a similar alert as when you try to change sites & have media loaded? (you have failed imgs that you can retry. they will be removed if you navigate away)
- disable html until images are either successfully added or removed.

**Comment by SergioEstevao** [comment]
I think this is now solved in 4.7 branch because of this PR https://github.com/wordpress-mobile/WordPress-iOS/pull/2943

**Comment by meremagee** [comment]
Nice - I'll check it out and close/edit accordingly once the PR is merged and shipped in an updated beta.

**Comment by meremagee** [comment]
Looks good, @SergioEstevao!
