### ISSUE TITLE
Legacy editor: pages published as posts

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#459]
Lower priority than new editor fixes.

Repro:
- go to me
- click on a blog
- click pages
- click + in the top right to add a new page
- add title and text
- hit publish
- note that page does not appear in pages list
- go to posts lists
- note that the "page" you just created was published as a post

**Comment by bummytime** [comment]
Fixed.

**Comment by SergioEstevao** [comment]
This is fixed on the 4.7 build.
