### ISSUE TITLE
Can update before remote img is swapped in for local

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#461]
Repro:
- add new post or page (or edit existing)
- add media in visual mode
- wait until fully uploaded as indicated by progress/opacity
- hit publish immediately after img is loaded
- don't get media-uploading blocker
- post publishes
- img fails upon load (square) - local img is still in html

You can also switch to html mode without getting the media-blocker immediately after the image uploads. If you do this, you'll see the local url in the src, and it appears to stall the upload. Thus, publishing the post from html, even if you wait a while/continue to edit beforehand, will publish the local/broken image.

video: https://lookback.io/watch/rmPmMDztH6y6uzaGb

**Comment by SergioEstevao** [comment]
This is fixed on the 4.7 build. By this PR https://github.com/wordpress-mobile/WordPress-iOS/pull/2943
