### ISSUE TITLE
Cursor set under keyboard

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#465]
If you type a single paragraph that extends beyond the visible text area, the cursor is not focused. Reported by a user and reproduced on iphone 5s, ios7

Repro
- create new post
- type a single, long paragraph that extends beyond the text area view
- notice that post does not scroll to focus where cursor is
- https://lookback.io/watch/WzmTtGfZcAPjXW3q4

note: may be resolved by fixes for https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/301, which I'm also still reproducing - will test both with next beta release

**Comment by meremagee** [comment]
verified that it happens across devices and iOS versions - repro consistently on ios7/iphone5s and ios8/ipadmini

**Comment by meoz** [comment]
Same issue on iPhone6, ios8

**Comment by diegoreymendez** [comment]
Fixed (although not included in v4.7 due to timing).
