### ISSUE TITLE
Publishing post with failed media items

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#469]
html for failed images not being cleaned upon state change

repro:
- create post
- add several images on a data/slow connection
- some fail
- publish post
- view post
- empty image containers remain

img containers in visual mode:
![](https://cloudup.com/ic9MgEZ1Fns+)

in html:
![](https://cloudup.com/ixTqKp5NOea+)

**Comment by SergioEstevao** [comment]
I this is also solved by this PR https://github.com/wordpress-mobile/WordPress-iOS/pull/3024

**Comment by SergioEstevao** [comment]
Do you still see this on the latest 4.8 release @meremagee?

**Comment by meremagee** [comment]
Looks great. Thx @SergioEstevao
