### ISSUE TITLE
CRASH: adding images from photostream

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#473]
adding images from an album on photostream crashes the app. adding from one that you do not own crashes the app _every time_

repro
- create post using button in footer from post list of primary blog
- type title
- type a few words
- hit add media icon
- go to photostream shared folder _created by someone else_
- add at least 1 photo from stream
- crash

logs from 3 repros in a row: https://cloudup.com/cezu061vqiq

**Comment by SergioEstevao** [comment]
@meremagee  Being able to add images from other people photo stream is a priority? I can a have a look on that... but I can also disable the option.

**Comment by bummytime** [comment]
> Being able to add images from other people photo stream is a priority?

Good question. My vote is no, or at least no for 4.7.

**Comment by meremagee** [comment]
sorry - had added when i was initially logging the crash, then after narrowing down to other people's streams, i didn't move it.

i don't have any data on this, but it doesn't seem _that_ far fetched that someone would add an image from a shared stream. there is no ownership indicator in the albums list > they all appear equally accessible, so having it crash 100% of the time is pretty awful.

moving to 4.8 as it's likely not a frequently hit flow

**Comment by meremagee** [comment]
No longer crashes. Nice! Opening a couple issues for refinement.
