### ISSUE TITLE
Contrast on failed media icon

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#474]
See @thianhlu's spec's below for "failed" notice on media

![](https://cloudup.com/iW85BfpGLoH+)

**Comment by thianhlu** [comment]
So the one in #427 and this one will prob end up the same. But really nothing to do other than make the background tint darker and blur the image a bit. There is also a slight drop-shadow on the text.

If they are doing it with css, you can do it with -webkit-filter: blur and -webkit-filter: grayscale

**Comment by SergioEstevao** [comment]
This is a failed image with the following filter parameters: -webkit-filter: blur(5px) grayscale(20%);

![screen shot 2015-01-16 at 09 56 42](https://cloud.githubusercontent.com/assets/651601/5774470/20edf738-9d66-11e4-9588-dd0d71b83096.png)

Good? @meremagee and @thianhlu

**Comment by thianhlu** [comment]
![](https://cloudup.com/ctHF-jMThK7+)

Let's try:
Background
-webkit-filter: blur(4px) grayscale(0.3);
Can we try and clip the borders/edges so they are not blurred? We would probably have to put inside a div like (http://stackoverflow.com/questions/12224320/defined-edges-with-css3-filter-blur).

Failed text
text-shadow: 0 1px 2px rgba(0,0,0,.06);
font-size: 20px

Retry Icon
opacity: 0.9;
background: #FFFFFF;
height: 54px
width 54px

Retry Icon circle
opacity: 0.9;
border: 4px solid #FFFFFF;
-webkit-border-radius: 60px
height: 120px
width 120px

Note we are going to use this same one on #427 cc @aerych

**Comment by bummytime** [comment]
> Can we try and clip the borders/edges so they are not blurred? We would probably have to put inside a div like (http://stackoverflow.com/questions/12224320/defined-edges-with-css3-filter-blur).

Great idea! Looks much more crisp.

![ygkk2](https://cloud.githubusercontent.com/assets/154014/5782177/beece31e-9d7e-11e4-97d3-e025a6e8820e.png)

**Comment by meremagee** [comment]
specs here https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/550
