### ISSUE TITLE
Edit format toolbar buttons in the editor

### ISSUE THREAD

**Issue by meoz** [wordpress-mobile/WordPress-iOS-Editor#480]
Hi,

Is there a way to remove or add format-buttons to the toolbar floating above the keyboard ?
I cant find any information or example for this.

**Comment by diegoreymendez** [comment]
There currently isn't any mechanism to do this.  The set of elements available is currently hard coded.  @meremagee and @thianhlu should be able to reply as to wether there are plans to bring this feature in.

**Comment by meremagee** [comment]
Configurability is something we have yet to discuss. It's not out of the question, but at this nascent point in the WYSIWYG editor's lifespan, stability is higher priority than customizability.

Tabled as far as internal dev goes, but let's circle back to configurable settings when we chat about web/native.

**Comment by meoz** [comment]
Ok , so I'll need to modify the sourcecode myself if I want to have buttons removed.
Thanks for the answer. Cheers.

**Comment by meremagee** [comment]
Closing for now to keep the repo streamlined. Will re-open when/if it becomes relevant for a specific release cycle.

@meoz - thanks for the suggestion & the initiative on modifying the sourcecode to meet your needs.
