### ISSUE TITLE
Show alert when max media insert reached

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS-Editor#486]
When adding images to a post we have a limit of 10 images for each insertion. When the user reach that limit there is no indication he simple cannot select anything more until he unselects a previous image.

We should show an alert explaining that the limit was reached and explain to the user that he needs to unselect something before selecting a new one.

**Comment by SergioEstevao** [comment]
![screen shot 2015-01-16 at 16 16 16](https://cloud.githubusercontent.com/assets/651601/5779503/2a120a68-9d9b-11e4-986c-335b5c4b0f50.png)

What do you think @meremagee ?

**Comment by bummytime** [comment]
@SergioEstevao I just ran your PR and have general comments which I'll just leave here so @meremagee can chime in too. Overall I like having the user know why the image selection just stops, so this is a good add IMHO.

1) Should "Need Help?" take the user somewhere? Right now it just dismisses the alert. Do we even need that option? Perhaps OK is enough??

2) @meremagee you kewl with the copy in this alert?

**Comment by meremagee** [comment]
throwing an alert here actually seems contrarian to apple's human interface guidelines, but seems like a totally reasonable interim solution: https://cloudup.com/iqzB3fMiWJY

1. Long-term preferred solution: graceful indication in UI. If we could fade/make un-selectable all images once the user has hit 10. Example: https://cloudup.com/iOly7pvDq2T

2. Short-term if faster/easier: alert. Let's go with single-button alert as @bummytime suggests.

**message**: You can only add 10 photos at a time
**confirm/dismiss**: OK

**Comment by meremagee** [comment]
single button alert is implemented, so closing for now - can look into more graceful ui implementation down the road
