### ISSUE TITLE
Turn on the new editor for all users

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS-Editor#497]
Title has it. In short, remove this logic: #126  and default to the new editor for all.

/cc @meremagee

**Comment by sendhil** [comment]
:boom:

**Comment by diegoreymendez** [comment]
@meremagee, @bummytime - Should users still see the option in settings to go back to the old editor?  I think it would be a good thing to offer them a chance to go back for the time being, but need confirmation on this.

**Comment by bummytime** [comment]
@diegoreymendez you are correct. We were planning on leaving the option in settings so users could revert if they chose to do so.

**Comment by meremagee** [comment]
Yup - the goal is to have fix the issues w/ the html view in new editor to meet the needs of users who prefer the legacy editor (related issues tagged #html), but at least for an interim period allow them to switch back in settings w/ the toggle!

**Comment by diegoreymendez** [comment]
Fixed.
