### ISSUE TITLE
Airplane mode + add image

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#498]
Attempting to publish a post that contains failed media in airplane mode yields awful (yet different) results on legacy & visual editors.

**Legacy editor**: crashes 100% of the time (log https://cloudup.com/iwWCi835LPe)
- turn on airplane mode
- create new post
- add title and text
- upload img
- get alert that you are offline & can't upload img
- tap OK on alert to dismiss
- tap publish
- get alert that media is in progress
- hit OK to publish anyway
- hang on screen
- tap publish again
- see no posts placeholder flash
- crash

**Visual editor**: wipes local draft contents
- turn on airplane mode
- create new post
- add title and text
- upload img
- img failure overlay on local img right away
- tap publish
- get alert that failed media will not be saved to post: https://cloudup.com/iqIFB2zAAYG
- in the background, note that upon getting alert, post contents have been reset
- hit OK to publish anyway
- post publish fails: https://cloudup.com/i8cnu94vj3J
- see "failed" local draft on posts lists (no title though one was initially set)
- open failed post > see "unsaved changes" alert: https://cloudup.com/iK6HuWBcHf0
- no contents in post

**Comment by bummytime** [comment]
This seems pretty serious. @SergioEstevao could you investigate this?

**Comment by SergioEstevao** [comment]
I will have a look
