### ISSUE TITLE
Shortcode embeds should render upon publish

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#504]
on the app, we're adding extra styling to shortcodes and embeddable links upon publish. we should be handling this like legacy editor.

if a link is pasted on a single line, it gets linked upon publish instead of embedded (like it does in other editors, including legacy mobile). 

if a shortcode is added, nothing is published at all and it gets this treatment in wp-admin: https://cloudup.com/iFx5KZ460OV

Legacy editor vs. visual editor: https://cloudup.com/cULwdiyxm68

---
in the future, we'll want a better ui for shortcodes/embeds in the visual ui (#85). Until then, we at least want them to work if manually entered.

**Comment by meremagee** [comment]
upon pasting a url, it is auto-linkified, even if it's an embed since we're not doing any server-side validation on-paste in the mobile app. 

If the user manually un-links the url within the _shortcode syntax_, it should embed just fine
![](https://cloudup.com/cNPQyYU1-fO+)

Note that adding urls on their own line to embed does not work on the ios app at the moment since we're re-linking it upon publish.

closing for now since shortcode works w/ manual unlink. will circle back when we think through a better ui generally.

**Comment by bummytime** [comment]
> Note that adding urls on their own line to embed does not work on the ios app at the moment since we're re-linking it upon publish.

@meremagee and I talked about this offline...just adding it here for the official record. In my current local 4.8 build, I am able to add a raw youtube URL (https://www.youtube.com/watch?v=gJ8O3mxlDkc), unlink it, and publish it. The video appears to embed properly in that published post.

**Comment by meremagee** [comment]
new behavior not working properly. logged new issue here https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/586
