### ISSUE TITLE
Continue showing onboarding until dismissed

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#510]
Per https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/466#issuecomment-71762880, to cover the case where the user updates WP iOS then opens the app > sees onboarding > immediately closes the app, let's persist the onboarding until they hit "Great, thanks."

**Comment by diegoreymendez** [comment]
Fixed.
