### ISSUE TITLE
Blank editor window.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS-Editor#514]
Steps to reproduce:

1. Launch WPiOS.
2. Make sure the visual editor is enabled.
3. Tap on the new post button in the navigation bar.
4. When the post editor comes up, click the X icon in the top left corner and discard all changes.
5. Tap again on the new post button in the navigation bar.

Current behaviour: the editor is blank and nothing can be written.
Expected behaviour: the editor should look as usual

**Comment by diegoreymendez** [comment]
@aerych - I was able to track this back to [this commit](https://github.com/wordpress-mobile/WordPress-iOS/commit/a5ec6aefc155a5f8dc10bd45ca860228add477a2).  I wasn't able to spot where it's coming from, but I imagine it may be because of some change in the editor pod code.

**Comment by diegoreymendez** [comment]
Here's [a video of the problem](https://cloudup.com/cVV5m-xiryV).  The video was not recorder in the latest version but in the commit reported in my previous message.

**Comment by diegoreymendez** [comment]
May be related to [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/515).

**Comment by meremagee** [comment]
I got this on my ipad2 (ios7) yesterday but when I try to repro on my iphone5s (ios7), the app crashes upon hitting new post 2nd time. Log: https://cloudup.com/cjE_NsiPmmI

**Comment by aerych** [comment]
Did some cursory testing. I can't reproduce this behavior on iOS 8 on a device, but I can on iOS 7.1.  However, there appears to be something more afoot.  
In the iOS 7 simulator I get a crash with the following message logged to the console:
```2015-01-29 11:00:19.768 WordPress[2485:60b] *** WebKit discarding exception: <CALayerInvalidGeometry> CALayer position contains NaN: [0 nan]
2015-01-29 11:00:19.822 WordPress[2485:60b] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [160 nan]```

On an iPhone 4 running iOS 7.1, I do not experience a crash, but where the app worked smoothly prior to opening the editor, after opening the editor a second time things very strange.  Here's a video:
https://cloudup.com/c7dGo1MrPhw

**Comment by aerych** [comment]
@diegoreymendez I've gone back through the commit history, testing the pod at various stages. The Core Animation related crash seems to have been introduced with 6ff4826a5129177cd03be7a5be95d1f869f912ec. It doesn't occur in commits prior to this.

**Comment by diegoreymendez** [comment]
@aerych - Thanks I'll follow up from that commit.

**Comment by aerych** [comment]
Diego and I tracked the crash down to two lines in `WPEditorView refreshVisibleViewportAndContentSize` (in the current develop branch). 
Calling either ` [self.webView stringByEvaluatingJavaScriptFromString:@"$(document.body).height();"];` or `self.webView.scrollView.contentSize = CGSizeMake(self.frame.size.width, newHeight);` seems to be the trigger, but never for the first time the editor is opened.

**Comment by bummytime** [comment]
@aerych nice sleuthing.

**Comment by aerych** [comment]
@diegoreymendez, just following up on our chat. I'm setting the assignment back to you. Tag!

**Comment by diegoreymendez** [comment]
@aerych - Just found that not calling any javascript code seems to fix it.  I'll upload and let you know so you can test it.  My goal here is to get to a point where the current solution is enough for us to be able to spend time in something more solid *cough* native *cough*.

**Comment by diegoreymendez** [comment]
Fixed.

**Comment by diegoreymendez** [comment]
Reopening until [this PR](https://github.com/wordpress-mobile/WordPress-iOS/compare/release/4.8...issue/editor-514-blank-editor?expand=1) is merged.
