### ISSUE TITLE
Onboarding: Small improvements to tip

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS-Editor#519]
As requested by @thianhlu in [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/466).

* [x] Lets change popup image. Here is are the images up to 3x: https://cloudup.com/cUj6itrkwMx
* [x] Make the line 0.5px tall
* [x] Use the latest text by mere "The WordPress app for iOS now includes a beautiful new visual editor. Try it out by creating a new post."

**Comment by diegoreymendez** [comment]
@meremagee - I have two questions on this issue:

1. Regarding the text, we currently have an almost similar message... should I still change it to match the message requested above?

```This version of the WordPress app includes a beautiful new visual editor. Try it out by creating a new post.```

2. The icons look kind of huge to me, is this the correct size?

![screen shot 2015-02-06 at 10 47 58 am](https://cloud.githubusercontent.com/assets/1836005/6080239/dd5ac60c-aded-11e4-9be3-33e429de0034.png)

**Comment by meremagee** [comment]
@meremagee - I have two questions on this issue:

> Regarding the text, we currently have an almost similar message... should I still change it to match the message requested above?
Yep - change to...
_The WordPress app for iOS now includes a beautiful new visual editor. Try it out by creating a new post._

> The icons look kind of huge to me, is this the correct size? If we want to keep this size I think I can add some additional spacing on top to make it look less cluttered.
- Keep as spec'ed here: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/466#issuecomment-71579195
- difficult for me to see what it looks like with the limited text bug on ios7 ^^

**Comment by thianhlu** [comment]
@diegoreymendez 

For logo: add 36px above and below.
Under copy: add 36px spacing below
Thin gray bar: 0.5px (let's see how that looks) as well as change color to #d2dee6 (WP Medium Gray)
Great thanks: Let's increase font-size to 16px (different than what i provided in mock)

Otherwise looks awesome

**Comment by meremagee** [comment]
> For logo: add 36px above and below.
> Under copy: add 36px spacing below.

@thianhlu - with added whitespace does not fit on horizontally positioned phone - thoughts?

**Comment by meremagee** [comment]
To make landscape-responsive, made decision to adjust img size & condense whitespace on slack. should be even whitespace above & below text & text width narrowed for better word flow.

![](https://cloudup.com/cL57OXdWA-y+)

**Comment by thianhlu** [comment]
good call
