### ISSUE TITLE
Retry UI

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#537]
If connection drops mid upload, "failed" not printed in retry img UI:

![](https://cloudup.com/ieIahtbanfQ+)

**Comment by SergioEstevao** [comment]
@meremagee  I think I did this on purpose for smaller devices, can you try to do the same in lansdcape mode on the same device?

**Comment by meremagee** [comment]
sometimes I have 2 images fail, one has the full overlay and one doesn't. assuming it's not device but img display size?

**Comment by meremagee** [comment]
addressed here in specs https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/550

same image w/ 2 different "retry" implementations https://cloudup.com/cLS7BcVwKBR
