### ISSUE TITLE
Img meta data - edit icon specs

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#549]
Tweaks to the style to meet @thianhlu's specs (noted that the pencil icon isn't centered & sizing appears off).

Background
-webkit-filter: blur(4px) grayscale(0.3);
Can we try and clip the borders/edges so they are not blurred? We would probably have to put inside a div like (http://stackoverflow.com/questions/12224320/defined-edges-with-css3-filter-blur).

Edit text
text-shadow: 0 1px 2px rgba(0,0,0,.06);
font-size: 20px

Edit Icon
opacity: 0.9;
background: #FFFFFF;
height: 54px
width 54px

Edit Icon circle
opacity: 0.9;
border: 4px solid #FFFFFF;
-webkit-border-radius: 60px
height: 120px
width 120px

**Comment by meremagee** [comment]
cc @aerych

**Comment by aerych** [comment]
It looks like the opacity was missing, and the edit text font size was using points instead of pixels.  The rest looks like it matches. 

> noted that the pencil icon isn't centered & sizing appears off

I'm not sure how to judge this one. It appears centered and sized according to the spec?

**Comment by meremagee** [comment]
cc @thianhlu - can you please give guidance/specs for centering/adjusting the icon? It is centered pixel-wise, but assuming you want it adjusted so that it looks balanced

**Comment by meremagee** [comment]
closing based on recent updates - we can re-open an issue re img centering/balancing for 4.9

**Comment by thianhlu** [comment]
What the latest look like?

**Comment by aerych** [comment]
Hiya Thian, 

A largish image shows the circle icon + text, a smaller image omits the circle if the spacing would be too tight.  The smallest images just show text.  Breaks are at a height of 200px (smallish) and 100px (very small). 

Here's how it looks currently:

![ios simulator screen shot feb 9 2015 7 27 23 pm](https://cloud.githubusercontent.com/assets/1435271/6119706/06b60b5a-b092-11e4-9e00-0c9a49fa444c.png)

![ios simulator screen shot feb 9 2015 6 02 59 pm](https://cloud.githubusercontent.com/assets/1435271/6118797/0bb81f04-b087-11e4-9611-8f41f04f97af.png)

**Comment by aerych** [comment]
Quick note: when I was getting the screen shots I noticed the pencil icon in the sans-circle version was much smaller than the pencil version in the circle version. I have this corrected locally (and reflected in the screen shots above) but I haven't pushed this to the repo pending any other changes @thianhlu might have.

**Comment by thianhlu** [comment]
Sizing and spacing seem a bit off and it is my fault cause I was giving some of those measurements above in @2x. Completely my fault.

We should simplify a bit and have only the 2 breakpoints for now. 
- For small, you can keep the same with just the label.
- For large and mid, they would be the same as @SergioEstevao latest version. You can use the same SVG sizing for circle as #559 like 
![](https://cloudup.com/c1hoaGDTVYi+)
