### ISSUE TITLE
Img meta data - refined specs (size)

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS-Editor#572]
Currently rendering at 2x size - should be same as retry: https://cloudup.com/crSuDuGnWqA

should have 2 breakpoints: 
- For small, keep the same with just the label. 
- For large & mid, they would be the same as @SergioEstevao latest version. You can use the same SVG sizing for circle as #559

cc @aerych

**Comment by meremagee** [comment]
I realized this is probably updated in dev, but I haven't seen the latest cut yet. Adding to "resolved > test" and closing for now.

**Comment by aerych** [comment]
Yah. Handled in #561 which tagged onto the end of #549 after it had closed.
